const endpoints = {
    FEEDBACK: process.env.REACT_APP_FEEDBACK_FORM_URL ?? "",
};

const FEEDBACK_FORM_SOURCE = "ASI_CHAIN_EXPLORER";
const MINIMUM_FEEDBACK_TEXT_LENGTH = 10;

export { endpoints, MINIMUM_FEEDBACK_TEXT_LENGTH, FEEDBACK_FORM_SOURCE };
